name: Fetch Bypass Alerts

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

env:
  RULESET_BYPASS_ALERTER_APPID: ${{ secrets.RULESET_BYPASS_ALERTER_APPID }}
  RULESET_BYPASS_ALERTER_INSTALLATIONID: ${{ secrets.RULESET_BYPASS_ALERTER_INSTALLATIONID }}
  RULESET_BYPASS_ALERTER_PRIVATEKEY: ${{ secrets.RULESET_BYPASS_ALERTER_PRIVATEKEY }}

jobs:
  fetch-bypass-alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Fetch Bypass Alerts
        run: node app.js